--
-- ER/Studio 8.0 SQL Code Generation
-- Company :      Facultad de Ingenier�a UNAM
-- Project :      MR_Proyecto_Final_Modulos.DM1
-- Author :      Borboa Castillo Carlos Alfonso, Ortiz Rivera Miguel Angel 
--
-- Date Created : Tuesday, June 04, 2024 12:33:51
-- Target DBMS : Oracle 11g
--

-- 
-- TABLE: CLIENTE 
--

connect boorproy/boorproy 

whenever sqlerror exit rollback

--MODULO 1 (CLIENTE -AZUL)
CREATE TABLE CLIENTE(
    CLIENTE_ID        NUMBER(7, 0)     NOT NULL,
    USUARIO           VARCHAR2(50)     NOT NULL,
    CONTRASEÑA        VARCHAR2(20)     NOT NULL,
    FECHA_REGISTRO    TIMESTAMP(2)     NOT NULL,
    EMAIL             VARCHAR2(100)    NOT NULL,
    TELEFONO          VARCHAR2(10)     NOT NULL,
    DIRECCION         VARCHAR2(100)    NOT NULL,
    TIPO              CHAR(1)          NOT NULL,
    CONSTRAINT CLIENTE_PK PRIMARY KEY (CLIENTE_ID)
    using index (
      create unique index cliente_pk on cliente(cliente_id) 
      tablespace indexes_clientes_tbs
    )
) tablespace clientes_tbs;



-- 
-- TABLE: TIPO_SERVICIO 
-- MÓDULO DOS (GRIS)

CREATE TABLE TIPO_SERVICIO(
    TIPO_SERVICIO_ID    NUMBER(2,0)     NOT NULL,
    DESCRIPCION         VARCHAR2(100)    NOT NULL,
    NOMBRE              VARCHAR2(40)     NOT NULL,
    CONSTRAINT TIPO_SERVICIO_PK PRIMARY KEY (TIPO_SERVICIO_ID)
	using index (
      create unique index TIPO_SERVICIO_PK on TIPO_SERVICIO(TIPO_SERVICIO_ID) 
      tablespace indexes_proveedores_tbs
    )
) tablespace proveedores_doc_tbs;




-- 
-- TABLE: NIVEL_ESTUDIO 
-- MÓDULO 2 (GRIS)

CREATE TABLE NIVEL_ESTUDIO(
    NIVEL_ESTUDIO_ID    NUMBER(2, 0)    NOT NULL,
    NIVEL_ESTUDIO       VARCHAR2(50)    NOT NULL,
    CONSTRAINT NIVEL_ESTUDIO_PK PRIMARY KEY (NIVEL_ESTUDIO_ID)
	using index (
      create unique index NIVEL_ESTUDIO_PK on NIVEL_ESTUDIO(NIVEL_ESTUDIO_ID) 
      tablespace indexes_proveedores_tbs
    )
) tablespace proveedores_inf_tbs;




-- 
-- TABLE: TIPO_STATUS_PROVEEDOR 
-- MÓDULO 2

CREATE TABLE TIPO_STATUS_PROVEEDOR(
    TIPO_STATUS_PROVEEDOR_ID    NUMBER(1, 0)    NOT NULL,
    STATUS                      VARCHAR2(30)    NOT NULL,
    CONSTRAINT TIPO_STATUS_PROVEEDOR_PK PRIMARY KEY (TIPO_STATUS_PROVEEDOR_ID)
	using index (
      create unique index TIPO_STATUS_PROVEEDOR_PK on TIPO_STATUS_PROVEEDOR(TIPO_STATUS_PROVEEDOR_ID) 
      tablespace indexes_proveedores_tbs
    )
) tablespace proveedores_inf_tbs;




-- 
-- TABLE: LUGAR_NACIMIENTO 
-- MÓDULO 2

CREATE TABLE LUGAR_NACIMIENTO(
    LUGAR_NACIMIENTO_ID    NUMBER(2, 0)    NOT NULL,
    ENTIDAD                VARCHAR2(50)    NOT NULL,
    CONSTRAINT LUGAR_NACIMIENTO_PK PRIMARY KEY (LUGAR_NACIMIENTO_ID)
	using index (
      create unique index LUGAR_NACIMIENTO_PK on LUGAR_NACIMIENTO(LUGAR_NACIMIENTO_ID) 
      tablespace indexes_proveedores_tbs
    )
) tablespace proveedores_inf_tbs
;



-- 
-- TABLE: PROVEEDOR 
-- MÓDULO 2

CREATE TABLE PROVEEDOR(
    PROVEEDOR_ID                NUMBER(4, 0)     NOT NULL,
    NOMBRE                      VARCHAR2(100)    NOT NULL,
    AP_PATERNO                  VARCHAR2(50)     NOT NULL,
    AP_MATERNO                  VARCHAR2(50),
    FOTO                        BLOB             NOT NULL,
    FECHA_NAC                   DATE             NOT NULL,
    DIRECCION                   VARCHAR2(100)    NOT NULL,
    TELEFONO_CASA               VARCHAR2(20),
    TELEFONO_MOVIL              VARCHAR2(20)     NOT NULL,
    EMAIL_REQUERIDO             VARCHAR2(60)     NOT NULL,
    FECHA_STATUS                TIMESTAMP (2)    NOT NULL,
    NIVEL_ESTUDIO_ID            NUMBER(2, 0)     NOT NULL,
    LUGAR_NACIMIENTO_ID         NUMBER(2, 0)     NOT NULL,
    TIPO_STATUS_PROVEEDOR_ID    NUMBER(1, 0)     NOT NULL,
    CONSTRAINT PROVEEDOR_PK PRIMARY KEY (PROVEEDOR_ID) 
	using index (
      create unique index PROVEEDOR_PK  on PROVEEDOR(PROVEEDOR_ID) 
      tablespace indexes_proveedores_tbs
    ),
	CONSTRAINT PROVEEDOR_NIVEL_ESTUDIO_ID_FK FOREIGN KEY (NIVEL_ESTUDIO_ID) REFERENCES NIVEL_ESTUDIO(NIVEL_ESTUDIO_ID),
	CONSTRAINT PROVEEDOR_TIPO_STATUS_PROVEEDOR_ID_FK FOREIGN KEY (TIPO_STATUS_PROVEEDOR_ID) REFERENCES TIPO_STATUS_PROVEEDOR(TIPO_STATUS_PROVEEDOR_ID),
	CONSTRAINT PROVEEDOR_LUGAR_NACIMIENTO_ID_FK FOREIGN KEY (LUGAR_NACIMIENTO_ID) REFERENCES LUGAR_NACIMIENTO(LUGAR_NACIMIENTO_ID)
) 
LOB (FOTO) STORE AS (TABLESPACE DATOS_BLOB_PROVEEDORES_TBS)
tablespace proveedores_inf_tbs
;

create index PROVEEDOR_NIVEL_ESTUDIO_ID_IX on PROVEEDOR(NIVEL_ESTUDIO_ID) tablespace indexes_proveedores_tbs;
create index PROVEEDOR_TIPO_STATUS_PROVEEDOR_ID_IX on PROVEEDOR(TIPO_STATUS_PROVEEDOR_ID) tablespace indexes_proveedores_tbs;
create index PROVEEDOR_LUGAR_NACIMIENTO_ID_IX on PROVEEDOR(LUGAR_NACIMIENTO_ID) tablespace indexes_proveedores_tbs;

-- 
-- TABLE: PROVEEDOR_SERVICIO 
-- MÓDULO 2

CREATE TABLE PROVEEDOR_SERVICIO(
    PROVEEDOR_SERVICIO_ID    NUMBER(4, 0)    NOT NULL,
    AÑOS_EXP                 NUMBER(2, 0)    NOT NULL,
    TIPO_SERVICIO_ID         NUMBER(2, 0)    NOT NULL,
    PROVEEDOR_ID             NUMBER(4, 0)    NOT NULL,
    CONSTRAINT PROVEEDOR_SERVICIO_PK PRIMARY KEY (PROVEEDOR_SERVICIO_ID)
	using index (
      create unique index PROVEEDOR_SERVICIO_PK on PROVEEDOR_SERVICIO(PROVEEDOR_SERVICIO_ID) 
      tablespace indexes_proveedores_tbs
    ), 
	CONSTRAINT PROVEEDOR_SERVICIO_TIPO_SERVICIO_ID_FK FOREIGN KEY (TIPO_SERVICIO_ID) REFERENCES TIPO_SERVICIO(TIPO_SERVICIO_ID),
	CONSTRAINT PROVEEDOR_SERVICIO_PROVEEDOR_ID_FK FOREIGN KEY (PROVEEDOR_ID) REFERENCES PROVEEDOR(PROVEEDOR_ID)
) tablespace proveedores_doc_tbs
;

create index PROVEEDOR_SERVICIO_TIPO_SERVICIO_ID_IX on PROVEEDOR_SERVICIO(TIPO_SERVICIO_ID) tablespace indexes_proveedores_tbs;
create index PROVEEDOR_SERVICIO_PROVEEDOR_ID_IX on PROVEEDOR_SERVICIO(PROVEEDOR_ID) tablespace indexes_proveedores_tbs;






-- 
-- TABLE: COMPROBANTE 
-- MÓDULO 2

CREATE TABLE COMPROBANTE(
    COMPROBANTE_ID           NUMBER(4, 0)    NOT NULL,
    COMPROBANTE              BLOB            NOT NULL,
    PROVEEDOR_SERVICIO_ID    NUMBER(4, 0)    NOT NULL,
    CONSTRAINT COMPROBANTE_PK PRIMARY KEY (COMPROBANTE_ID)
	using index (
      create unique index COMPROBANTE_PK on COMPROBANTE(COMPROBANTE_ID) 
      tablespace indexes_proveedores_tbs
    ),
    CONSTRAINT 	COMPROBANTE_PROVEEDOR_SERVICIO_ID_FK FOREIGN KEY (PROVEEDOR_SERVICIO_ID) REFERENCES PROVEEDOR_SERVICIO(PROVEEDOR_SERVICIO_ID)
) 
LOB (COMPROBANTE) STORE AS (TABLESPACE DATOS_BLOB_PROVEEDORES_TBS)
tablespace proveedores_doc_tbs
;

create index COMPROBANTE_PROVEEDOR_SERVICIO_ID_IX on COMPROBANTE(PROVEEDOR_SERVICIO_ID) tablespace indexes_proveedores_tbs;





-- 
-- TABLE: CUENTA_BANCARIA_PROVEEDOR 
-- MÓDULO 2

CREATE TABLE CUENTA_BANCARIA_PROVEEDOR(
    CUENTA_BANCARIA_PROVEEDOR_ID    NUMBER(4, 0)    NOT NULL,
    CLABE                           VARCHAR2(18)    NOT NULL,
    NOMBRE_BANCO                    VARCHAR2(30)    NOT NULL,
    PROVEEDOR_ID                    NUMBER(4, 0)    NOT NULL,
    CONSTRAINT CUENTA_BANCARIA_PROVEEDOR_PK PRIMARY KEY (CUENTA_BANCARIA_PROVEEDOR_ID)
	using index (
      create unique index CUENTA_BANCARIA_PROVEEDOR_PK on CUENTA_BANCARIA_PROVEEDOR(CUENTA_BANCARIA_PROVEEDOR_ID) 
      tablespace indexes_proveedores_tbs
    ),
	CONSTRAINT CUENTA_BANCARIA_PROVEEDOR_PROVEEDOR_ID_FK FOREIGN KEY (PROVEEDOR_ID) REFERENCES PROVEEDOR(PROVEEDOR_ID)
) tablespace datos_bancarios_proveedor_tbs
;

create index CUENTA_BANCARIA_PROVEEDOR_PROVEEDOR_ID_IX on CUENTA_BANCARIA_PROVEEDOR(PROVEEDOR_ID) tablespace indexes_proveedores_tbs;






-- 
-- TABLE: DOCUMENTO_PROVEEDOR 
-- MÓDULO 2


CREATE TABLE DOCUMENTO_PROVEEDOR(
    DOCUMENTO_PROVEEDOR_ID    NUMBER(4, 0)    NOT NULL,
    INE                       BLOB            NOT NULL,
    COMPROBANTE_DOM           BLOB            NOT NULL,
    PROVEEDOR_ID              NUMBER(4, 0)    NOT NULL,
    CONSTRAINT DOCUMENTO_PROVEEDOR_PK PRIMARY KEY (DOCUMENTO_PROVEEDOR_ID)
	using index (
      create unique index DOCUMENTO_PROVEEDOR_PK on DOCUMENTO_PROVEEDOR(DOCUMENTO_PROVEEDOR_ID) 
      tablespace indexes_proveedores_tbs
    ), 
	CONSTRAINT DOCUMENTO_PROVEEDOR_PROVEEDOR_ID_FK FOREIGN KEY (PROVEEDOR_ID) REFERENCES PROVEEDOR(PROVEEDOR_ID)
) 
LOB (INE) STORE AS (TABLESPACE DATOS_BLOB_PROVEEDORES_TBS)
LOB (COMPROBANTE_DOM) STORE AS (TABLESPACE DATOS_BLOB_PROVEEDORES_TBS)
tablespace proveedores_doc_tbs
;


create index DOCUMENTO_PROVEEDOR_PROVEEDOR_ID_IX on DOCUMENTO_PROVEEDOR(PROVEEDOR_ID) tablespace indexes_proveedores_tbs;





-- 
-- TABLE: EMAIL 
-- MÓDULO 2

CREATE TABLE EMAIL(
    EMAIL_ID        NUMBER(4, 0)    NOT NULL,
    EMAIL           VARCHAR2(60)    NOT NULL,
    PROVEEDOR_ID    NUMBER(4, 0)    NOT NULL,
    CONSTRAINT EMAIL_PK PRIMARY KEY (EMAIL_ID)
	using index (
      create unique index EMAIL_PK on EMAIL(EMAIL_ID) 
      tablespace indexes_proveedores_tbs
    ), 
	CONSTRAINT EMAIL_PROVEEDOR_ID_FK FOREIGN KEY (PROVEEDOR_ID) REFERENCES PROVEEDOR(PROVEEDOR_ID)
) tablespace proveedores_inf_tbs
;

create index EMAIL_PROVEEDOR_ID_IX on EMAIL(PROVEEDOR_ID) tablespace indexes_proveedores_tbs;




-- 
-- TABLE: EMPRESA 
-- MÓDULO 1

CREATE TABLE EMPRESA(
    CLIENTE_ID       NUMBER(7, 0)     NOT NULL,
    NOMBRE           VARCHAR2(100)    NOT NULL,
    NUM_EMPLEADOS    NUMBER(4, 0)     NOT NULL,
    DESCRIPCION      VARCHAR2(100)    NOT NULL,
    LOGOTIPO         BLOB             NOT NULL,
    CONSTRAINT CLIENTE_EMPRESA_PK PRIMARY KEY (CLIENTE_ID)
	using index (
      create unique index CLIENTE_EMPRESA_PK on EMPRESA(CLIENTE_ID) 
      tablespace indexes_clientes_tbs
    ), 
	CONSTRAINT EMPRESA_CLIENTE_ID_FK FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTE(CLIENTE_ID)
) 
LOB (LOGOTIPO) STORE AS (TABLESPACE DATOS_BLOB_CLIENTES_TBS)
tablespace clientes_tbs
;

--create index EMPRESA_CLIENTE_ID_IX on EMPRESA(CLIENTE_ID) tablespace indexes_clientes_tbs; --NO FUNCIONA PORQUE LA PK YA TIENE ESE CAMPO INDEXADO




-- 
-- TABLE: STATUS_SERVICIO 
-- MÓDULO 1

CREATE TABLE STATUS_SERVICIO(
    STATUS_SERVICIO_ID    NUMBER(1, 0)     NOT NULL,
    DESCRIPCION           VARCHAR2(100)    NOT NULL,
    NOMBRE                VARCHAR2(20)     NOT NULL,
    CONSTRAINT STATUS_SERVICIO_PK PRIMARY KEY (STATUS_SERVICIO_ID)
	using index (
      create unique index STATUS_SERVICIO_PK on STATUS_SERVICIO(STATUS_SERVICIO_ID) 
      tablespace indexes_clientes_tbs
    )
) tablespace SERVICIO_TBS
;



-- 
-- TABLE: PERSONA 
-- MÓDULO 1

CREATE TABLE PERSONA(
    CLIENTE_ID    NUMBER(7, 0)     NOT NULL,
    CURP          VARCHAR2(18)     NOT NULL,
    NOMBRE        VARCHAR2(100)    NOT NULL,
    AP_PATERNO    VARCHAR2(50)     NOT NULL,
    AP_MATERNO    VARCHAR2(50),
    FECHA_NAC     DATE             NOT NULL,
    FOTO          BLOB             NOT NULL,
    CONSTRAINT CLIENTE_PERSONA_PK PRIMARY KEY (CLIENTE_ID)
	using index (
      create unique index cliente_persona_pk on PERSONA(cliente_id) 
      tablespace indexes_clientes_tbs
    ), 
	CONSTRAINT PERSONA_CLIENTE_ID_FK FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTE(CLIENTE_ID)
) 
LOB (FOTO) STORE AS (TABLESPACE DATOS_BLOB_CLIENTES_TBS)
tablespace clientes_tbs
;

--create index PERSONA_CLIENTE_ID_IX on PERSONA(CLIENTE_ID) tablespace indexes_clientes_tbs; --NO SE PUEDE ANEXAR EL CAMPO PORQUE YA LO HIZO LA PK







-- 
-- TABLE: SERVICIO 
-- MÓDULO 1

CREATE TABLE SERVICIO(
    SERVICIO_ID               NUMBER(10, 0)     NOT NULL,
    FECHA_DE_SOLICITUD        TIMESTAMP (2)     NOT NULL,
    DESCRIPCION               VARCHAR2(1000)    NOT NULL,
    DESCRIPCION_PDF           BLOB,
    FECHA_PROGRESO            TIMESTAMP (2)     NOT NULL,
    PROVEEDOR_SERVICIO_RID    NUMBER(4, 0)      NOT NULL,
    CLIENTE_ID                NUMBER(7, 0)      NOT NULL,
    STATUS_SERVICIO_ID        NUMBER(1, 0)      NOT NULL,
    CONSTRAINT SERVICIO_PK PRIMARY KEY (SERVICIO_ID)
	using index (
      create unique index SERVICIO_PK on SERVICIO(SERVICIO_ID) 
      tablespace indexes_clientes_tbs
    ), 
	CONSTRAINT SERVICIO_STATUS_SERVICIO_ID_FK FOREIGN KEY (STATUS_SERVICIO_ID) REFERENCES STATUS_SERVICIO(STATUS_SERVICIO_ID),
	CONSTRAINT SERVICIO_CLIENTE_ID_FK FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTE(CLIENTE_ID)
) 
LOB (DESCRIPCION_PDF) STORE AS (TABLESPACE DATOS_BLOB_CLIENTES_TBS)
tablespace SERVICIO_TBS
;


create index SERVICIO_STATUS_SERVICIO_ID_IX on SERVICIO(STATUS_SERVICIO_ID) tablespace indexes_clientes_tbs;
create index PERSONA_CLIENTE_ID_IX on SERVICIO(CLIENTE_ID) tablespace indexes_clientes_tbs;







-- 
-- TABLE: SERVICIO_ACEPTADO 
-- MÓDULO 1

CREATE TABLE SERVICIO_ACEPTADO(
    SERVICIO_ID              NUMBER(10, 0)    NOT NULL,
    INSTRUCCIONES_CLIENTE    VARCHAR2(100)    NOT NULL,
    PRECIO                   NUMBER(5, 0)     NOT NULL,
    NUM_MENSUALIDADES        SMALLINT,
    CONSTRAINT SERVICIO_ACEPTADO_SERVICIO_PK PRIMARY KEY (SERVICIO_ID)
	using index (
      create unique index SERVICIO_ACEPTADO_SERVICIO_PK on SERVICIO_ACEPTADO(SERVICIO_ID) 
      tablespace indexes_clientes_tbs
    ),
    CONSTRAINT SERVICIO_ACEPTADO_SERVICIO_ID_FK FOREIGN KEY (SERVICIO_ID) REFERENCES SERVICIO(SERVICIO_ID)
) tablespace SERVICIO_TBS
;


--create index SERVICIO_ACEPTADO_SERVICIO_ID_IX on SERVICIO_ACEPTADO(SERVICIO_ID) tablespace indexes_clientes_tbs; --NO SE PUEDE ANEXAR EL CAMPO PORQUE YA LO HIZO LA PK







-- 
-- TABLE: EVALUACION_SERVICIO 
-- MÓDULO 1

CREATE TABLE EVALUACION_SERVICIO(
    EVALUACION_SERVICIO_ID    NUMBER(7, 0)     NOT NULL,
    CALIFICACION              SMALLINT         NOT NULL,
    COMENTARIO                VARCHAR2(150)    NOT NULL,
    SERVICIO_ID               NUMBER(10, 0)    NOT NULL,
    CONSTRAINT EVALUACION_SERVICIO_PK PRIMARY KEY (EVALUACION_SERVICIO_ID)
	using index (
      create unique index EVALUACION_SERVICIO_PK on EVALUACION_SERVICIO(EVALUACION_SERVICIO_ID) 
      tablespace indexes_clientes_tbs
    ), 
	CONSTRAINT EVALUACION_SERVICIO_SERVICIO_ID_FK FOREIGN KEY (SERVICIO_ID) REFERENCES SERVICIO_ACEPTADO(SERVICIO_ID)
) tablespace SERVICIO_TBS
;


create index EVALUACION_SERVICIO_SERVICIO_ID_IX on EVALUACION_SERVICIO(SERVICIO_ID) tablespace indexes_clientes_tbs;





-- 
-- TABLE: HISTORICO_STATUS_PROVEEDOR 
-- MÓDULO 2

CREATE TABLE HISTORICO_STATUS_PROVEEDOR(
    HISTORICO_STATUS_PROVEEDOR_ID    NUMBER(5, 0)    NOT NULL,
    FECHA_STATUS                     TIMESTAMP (2)        NOT NULL,
    TIPO_STATUS_PROVEEDOR_ID         NUMBER(1, 0)    NOT NULL,
    PROVEEDOR_ID                     NUMBER(4, 0)    NOT NULL,
    CONSTRAINT HISTORICO_STATUS_PROVEEDOR_PK PRIMARY KEY (HISTORICO_STATUS_PROVEEDOR_ID)
	using index (
      create unique index HISTORICO_STATUS_PROVEEDOR_PK on HISTORICO_STATUS_PROVEEDOR(HISTORICO_STATUS_PROVEEDOR_ID) 
      tablespace indexes_proveedores_tbs
    ), 
	CONSTRAINT HISTORICO_STATUS_PROVEEDOR_PROVEEDOR_ID_FK FOREIGN KEY (PROVEEDOR_ID) REFERENCES PROVEEDOR(PROVEEDOR_ID),
	CONSTRAINT HISTORICO_STATUS_PROVEEDOR_TIPO_STATUS_PROVEEDOR_ID_FK FOREIGN KEY (TIPO_STATUS_PROVEEDOR_ID) REFERENCES TIPO_STATUS_PROVEEDOR(TIPO_STATUS_PROVEEDOR_ID)
) tablespace proveedores_inf_tbs
;


create index HISTORICO_STATUS_PROVEEDOR_PROVEEDOR_ID_IX on HISTORICO_STATUS_PROVEEDOR(PROVEEDOR_ID) tablespace indexes_proveedores_tbs;
create index HISTORICO_STATUS_PROVEEDOR_TIPO_STATUS_PROVEEDOR_ID_IX on HISTORICO_STATUS_PROVEEDOR(TIPO_STATUS_PROVEEDOR_ID) tablespace indexes_proveedores_tbs;










-- 
-- TABLE: HISTORICO_STATUS_SERVICIO 
-- MÓDULO 1

CREATE TABLE HISTORICO_STATUS_SERVICIO(
    HISTORICO_STATUS_SERVICIO_ID    NUMBER(10, 0)    NOT NULL,
    FECHA_STATUS                    TIMESTAMP (2)    NOT NULL,
    SERVICIO_ID                     NUMBER(10, 0)    NOT NULL,
    STATUS_SERVICIO_ID              NUMBER(1, 0)     NOT NULL,
    CONSTRAINT HISTORICO_STATUS_SERVICIO_PK PRIMARY KEY (HISTORICO_STATUS_SERVICIO_ID)
	using index (
      create unique index HISTORICO_STATUS_SERVICIO_PK on HISTORICO_STATUS_SERVICIO(HISTORICO_STATUS_SERVICIO_ID) 
      tablespace indexes_clientes_tbs
    ), 
	CONSTRAINT HISTORICO_STATUS_SERVICIO_STATUS_SERVICIO_ID_FK FOREIGN KEY (STATUS_SERVICIO_ID) REFERENCES STATUS_SERVICIO(STATUS_SERVICIO_ID),
	CONSTRAINT HISTORICO_STATUS_SERVICIO_SERVICIO_ID_FK FOREIGN KEY (SERVICIO_ID) REFERENCES SERVICIO(SERVICIO_ID)
) tablespace SERVICIO_TBS
;


create index HISTORICO_STATUS_SERVICIO_STATUS_SERVICIO_ID_IX on HISTORICO_STATUS_SERVICIO(STATUS_SERVICIO_ID) tablespace indexes_clientes_tbs;
create index HISTORICO_STATUS_SERVICIO_SERVICIO_ID_IX on HISTORICO_STATUS_SERVICIO(SERVICIO_ID) tablespace indexes_clientes_tbs;










-- 
-- TABLE: TARJETA_CLIENTE 
-- MÓDULO 1

CREATE TABLE TARJETA_CLIENTE(
    TARJETA_CLIENTE_ID    NUMBER(4, 0)    NOT NULL,
    CLABE                 VARCHAR2(18)    NOT NULL,
    PROPIETARIO           VARCHAR2(50),
    FECHA                 DATE,
    CVV                   VARCHAR2(3),
    CLIENTE_ID            NUMBER(7, 0)    NOT NULL,
    CONSTRAINT TARJETA_CLIENTE_PK PRIMARY KEY (TARJETA_CLIENTE_ID)
	using index (
      create unique index TARJETA_CLIENTE_PK on TARJETA_CLIENTE(TARJETA_CLIENTE_ID) 
      tablespace indexes_clientes_tbs
    ), 
    CONSTRAINT TARJETA_CLIENTE_CLIENTE_ID_FK FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTE(CLIENTE_ID)
) tablespace DATOS_BANCARIOS_CLIENTES_TBS
;

create index TARJETA_CLIENTE_CLIENTE_ID_IX on TARJETA_CLIENTE(CLIENTE_ID) tablespace indexes_clientes_tbs;





-- 
-- TABLE: PAGO_SERVICIO 
-- MÓDULO 1


CREATE TABLE PAGO_SERVICIO(
    SERVICIO_ID           NUMBER(10, 0)    NOT NULL,
    NUM_PAGO              SMALLINT         NOT NULL,
    IMPORTE               NUMBER(5, 0)     NOT NULL,
    COMISION              NUMBER(5, 0)     NOT NULL,
    FECHA_PAGO            TIMESTAMP (2)    NOT NULL,
    TARJETA_CLIENTE_ID    NUMBER(4, 0)     NOT NULL,
    CONSTRAINT PAGO_SERVICIO_PK PRIMARY KEY (SERVICIO_ID, NUM_PAGO)
	using index (
      create unique index PAGO_SERVICIO_PK on PAGO_SERVICIO(SERVICIO_ID, NUM_PAGO) 
      tablespace indexes_clientes_tbs
    ), 
	CONSTRAINT PAGO_SERVICIO_SERVICIO_ID_FK FOREIGN KEY (SERVICIO_ID) REFERENCES SERVICIO_ACEPTADO(SERVICIO_ID),
    CONSTRAINT PAGO_SERVICIO_TARJETA_CLIENTE_ID_FK FOREIGN KEY (TARJETA_CLIENTE_ID) REFERENCES TARJETA_CLIENTE(TARJETA_CLIENTE_ID)
) tablespace DATOS_BANCARIOS_CLIENTES_TBS
;

create index PAGO_SERVICIO_SERVICIO_ID_IX on PAGO_SERVICIO(SERVICIO_ID) tablespace indexes_clientes_tbs;
create index PAGO_SERVICIO_TARJETA_CLIENTE_ID_IX on PAGO_SERVICIO(TARJETA_CLIENTE_ID) tablespace indexes_clientes_tbs;






-- 
-- TABLE: PROVEEDOR_DEPÓSITO 
-- MÓDULO 2

CREATE TABLE PROVEEDOR_DEPOSITO(
    PROVEEDOR_DEPOSITO_ID           NUMBER(5, 0)     NOT NULL,
    IMPORTE                         NUMBER(5, 0)     NOT NULL,
    BANCO                           VARCHAR2(30)     NOT NULL,
    FECHA_PAGO                      TIMESTAMP (2)         NOT NULL,
    COMPROBANTE_PAGO                BLOB             NOT NULL,
    CUENTA_BANCARIA_PROVEEDOR_ID    NUMBER(4, 0)     NOT NULL,
    SERVICIO_RID                    NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PROVEEDOR_DEPOSITO_PK PRIMARY KEY (PROVEEDOR_DEPOSITO_ID)
	using index (
      create unique index PROVEEDOR_DEPOSITO_PK on PROVEEDOR_DEPOSITO(PROVEEDOR_DEPOSITO_ID) 
      tablespace indexes_proveedores_tbs
    ), 
	CONSTRAINT PROVEEDOR_DEPOSITO_CUENTA_BANCARIA_PROVEEDOR_ID_FK FOREIGN KEY (CUENTA_BANCARIA_PROVEEDOR_ID) REFERENCES CUENTA_BANCARIA_PROVEEDOR(CUENTA_BANCARIA_PROVEEDOR_ID)
) 
LOB (COMPROBANTE_PAGO) STORE AS (TABLESPACE DATOS_BLOB_PROVEEDORES_TBS)
tablespace datos_bancarios_proveedor_tbs
;


create index PROVEEDOR_DEPOSITO_CUENTA_BANCARIA_PROVEEDOR_ID_IX on PROVEEDOR_DEPOSITO(CUENTA_BANCARIA_PROVEEDOR_ID) tablespace indexes_proveedores_tbs;






-- 
-- TABLE: SERVICIO_EVIDENCIA 
-- MÓDULO 2

CREATE TABLE SERVICIO_EVIDENCIA(
    SERVICIO_EVIDENCIA_ID    NUMBER(4, 0)     NOT NULL,
    DESCRIPCION              VARCHAR2(100)    NOT NULL,
    FECHA_REALIZACION        DATE             NOT NULL,
    PROVEEDOR_SERVICIO_ID    NUMBER(4, 0)     NOT NULL,
    CONSTRAINT SERVICIO_EVIDENCIA_PK PRIMARY KEY (SERVICIO_EVIDENCIA_ID)
	using index (
      create unique index SERVICIO_EVIDENCIA_PK on SERVICIO_EVIDENCIA(SERVICIO_EVIDENCIA_ID) 
      tablespace indexes_proveedores_tbs
    ),
    CONSTRAINT SERVICIO_EVIDENCIA_PROVEEDOR_SERVICIO_ID_FK FOREIGN KEY (PROVEEDOR_SERVICIO_ID) REFERENCES PROVEEDOR_SERVICIO(PROVEEDOR_SERVICIO_ID)
) tablespace proveedores_doc_tbs
;


create index SERVICIO_EVIDENCIA_PROVEEDOR_SERVICIO_ID_IX on SERVICIO_EVIDENCIA(PROVEEDOR_SERVICIO_ID) tablespace indexes_proveedores_tbs;




-- 
-- TABLE: SERVICIO_IMAGEN 
-- MÓDULO 2

CREATE TABLE SERVICIO_IMAGEN(
    SERVICIO_IMAGEN_ID       NUMBER(4, 0)     NOT NULL,
    IMAGEN                   BLOB             NOT NULL,
    DESCRIPCION              VARCHAR2(500)    NOT NULL,
    SERVICIO_EVIDENCIA_ID    NUMBER(4, 0)     NOT NULL,
    CONSTRAINT SERVICIO_IMAGEN_PK PRIMARY KEY (SERVICIO_IMAGEN_ID)
	using index (
      create unique index SERVICIO_IMAGEN_PK on SERVICIO_IMAGEN(SERVICIO_IMAGEN_ID) 
      tablespace indexes_proveedores_tbs
    ), 
	CONSTRAINT SERVICIO_IMAGEN_SERVICIO_EVIDENCIA_ID_FK FOREIGN KEY (SERVICIO_EVIDENCIA_ID) REFERENCES SERVICIO_EVIDENCIA(SERVICIO_EVIDENCIA_ID)
) 
LOB (IMAGEN) STORE AS (TABLESPACE DATOS_BLOB_PROVEEDORES_TBS)
tablespace proveedores_doc_tbs
;

create index SERVICIO_IMAGEN_SERVICIO_EVIDENCIA_ID_IX on SERVICIO_IMAGEN(SERVICIO_EVIDENCIA_ID) tablespace indexes_proveedores_tbs;

/*
select owner, table_name,tablespace_name 
from dba_tables
where owner ='BOORPROY'
order by tablespace_name; 

select owner,index_name,tablespace_name,index_type,table_name,uniqueness
from dba_indexes
where owner ='BOORPROY';
*/
