CREATE TABLE BANK (
    BANK_ID              NUMBER NOT NULL,
    BANK_NAME            VARCHAR(20) NOT NULL,
    CONSTRAINT BANK_PK PRIMARY KEY (BANK_ID)
);

CREATE TABLE CARD (
    CARD_ID                 NUMBER NOT NULL,
    CARD_NUMBER             NUMBER NOT NULL,
    CARD_EXPIRATION_DATE    NUMBER(4) NOT NULL,
    CARD_EXPIRATION_MONTH   NUMBER(2) NOT NULL,
    CARD_CVV                NUMBER(3) NOT NULL,
    CARD_CLIENT_ID          NUMBER NOT NULL,
    CONSTRAINT CARD_PK PRIMARY KEY (CARD_ID),
    CONSTRAINT CARD_CARD_CLIENT_ID_FK FOREIGN KEY (CARD_CLIENT_ID) REFERENCES CLIENT (CLIENT_USER_ID)
);

CREATE TABLE USER (
    USER_ID              NUMBER NOT NULL,
    USER_USERNAME        VARCHAR2(20) NOT NULL,
    USER_PASSWORD        VARCHAR2(20) NOT NULL,
    USER_EMAIL           VARCHAR2(20) NOT NULL,
    USER_IS_CLIENT       NUMBER NOT NULL,
    USER_IS_DEALER       NUMBER NOT NULL,
    USER_IS_PROVIDER     NUMBER NOT NULL,
    CONSTRAINT USER_PK PRIMARY KEY (USER_ID)
);

CREATE TABLE CLIENT (
    CLIENT_USER_ID       NUMBER NOT NULL,
    CLIENT_NAME          VARCHAR2(20) NOT NULL,
    CLIENT_LASTNAME      VARCHAR2(20) NOT NULL,
    CLIENT_PHOTO         BLOB NOT NULL,
    CLIENT_BIRTHDATE     DATE NOT NULL,
    CLIENT_ADDRESS       VARCHAR2(30) NULL,
    CLIENT_LATITUDE      FLOAT NULL,
    CLIENT_LONGITUDE     FLOAT NULL,
    CONSTRAINT CLIENT_PK PRIMARY KEY (CLIENT_USER_ID),
    CONSTRAINT CLIENT_USER_ID_FK FOREIGN KEY (CLIENT_USER_ID) REFERENCES USER(USER_ID) ON DELETE CASCADE
);

CREATE TABLE DEALER (
    DEALER_USER_ID              NUMBER NOT NULL,
    DEALER_NAME                 VARCHAR2(20) NOT NULL,
    DEALER_LASTNAME             VARCHAR2(20) NOT NULL,
    DEALER_PHOTO                BLOB NOT NULL,
    DEALER_BIRTHDATE            DATE NOT NULL,
    DEALER_LICENSE_NUMBER       NUMBER(6) NOT NULL,
    DEALER_LICENSE_STARTDATE    DATE NOT NULL,
    DEALER_LICENSE_END_DATE     DATE NOT NULL,
    DEALER_MOTORCYCLE_PLATE     VARCHAR2(20) NULL,
    DEALER_MOTORCYCLE_PHOTO     BLOB NOT NULL,
    DEALER_SUBSTITUTE_ID        NUMBER NULL,
    CONSTRAINT DEALER_PK PRIMARY KEY (USER_ID),
    CONSTRAINT DEALER_DEALER_SUBSTITUTE_ID_FK FOREIGN KEY (DEALER_SUBSTITUTE_ID) REFERENCES DEALER (DEALER_USER_ID) ON DELETE SET NULL,
    CONSTRAINT DEALER_USER_ID_FK FOREIGN KEY (DEALER_USER_ID) REFERENCES USER(USER_ID) ON DELETE CASCADE
);

CREATE TABLE DEALER_BANK_DATA (
    DEALER_BANK_DATA_ID         NUMBER NOT NULL,
    DEALER_BANK_DATA_CLABE      VARCHAR(16) NOT NULL,
    DEALER_BANK_DATA_FREQUENCY  VARCHAR2(20) NOT NULL CHECK (DEALER_BANK_DATA_FREQUENCY_CHK IN ('BIWEEKLY', 'WEEKLY', 'DAILY')),
    DEALER_BANK_DEALER_ID       NUMBER NOT NULL,
    DEALER_BANK_DATA_BANK_ID    NUMBER NOT NULL,
    CONSTRAINT DEALER_BANK_DATA_PK PRIMARY KEY (DEALER_BANK_DATA_ID),
    CONSTRAINT DEALER_BANK_DATA_DEALER_ID_FK FOREIGN KEY (DEALER_BANK_DEALER_ID) REFERENCES DEALER (DEALER_USER_ID),
    CONSTRAINT DEALER_BANK_DATA_BANK_ID_FK FOREIGN KEY (DEALER_BANK_DATA_BANK_ID) REFERENCES BANK (BANK_ID) ON DELETE SET NULL
);

CREATE TABLE DEALER_PAYMENT (
    DEALER_PAYMENT_ID           NUMBER NOT NULL,
    DEALER_PAYMENT_AMOUNT       FLOAT NOT NULL,
    DEALER_PAYMENT_DATE         DATE NOT NULL,
    DEALER_PAYMENT_DEALER_ID    NUMBER NOT NULL,
    DEALER_PAYMENT_ORDER_ID     NUMBER NOT NULL,
    CONSTRAINT DEALER_PAYMENT_PK PRIMARY KEY (DEALER_PAYMENT_ID),
    CONSTRAINT DEALER_PAYMENT_ORDER_ID_FK FOREIGN KEY (DEALER_PAYMENT_ORDER_ID) REFERENCES ORDER (ORDER_ID) ON DELETE SET NULL,
    CONSTRAINT DEALER_PAYMENT_DEALER_ID_FK FOREIGN KEY (DEALER_PAYMENT_DEALER_ID) REFERENCES DEALER (DEALER_USER_ID)
);

CREATE TABLE LOCATION_LOG (
    LOCATION_LOG_ID         NUMBER NOT NULL,
    LOCATION_LOG_TIMESTAMP  DATE NOT NULL,
    LOCATION_LOG_LATITUDE   FLOAT NOT NULL,
    LOCATION_LOG_LONGITUDE  FLOAT NOT NULL,
    LOCATION_LOG_USER_ID    NUMBER NOT NULL,
    CONSTRAINT LOCATION_LOG_PK PRIMARY KEY (LOCATION_LOG_ID),
    CONSTRAINT LOCATION_LOG_LOCATION_LOG_USER_ID_FK FOREIGN KEY (LOCATION_LOG_USER_ID) REFERENCES DEALER (DEALER_USER_ID)
);

CREATE TABLE DISH (
    DISH_ID              NUMBER NOT NULL,
    DISH_NAME            VARCHAR2(20) NOT NULL,
    DISH_CATEGORY        VARCHAR2(20) NOT NULL CHECK (DISH_DISH_CATEGORY_CHK IN ('BREAKFAST', 'LUNCH', 'DINNER')),
    DISH_DESCRIPTION     VARCHAR2(200) NOT NULL,
    DISH_CALORIES        NUMBER NULL,
    DISH_VIDEO           BLOB NULL,
    DISH_LAST_PRICE      FLOAT NOT NULL,
    DISH_LAST_PRICE_DATE DATE NOT NULL,
    DISH_TYPE_ID         NUMBER NOT NULL,
    DISH_PROVIDER_USER_ID NUMBER NOT NULL,
    CONSTRAINT DISH_PK PRIMARY KEY (DISH_ID),
    CONSTRAINT DISH_DISH_TYPE_ID_FK FOREIGN KEY (DISH_TYPE_ID) REFERENCES DISH_TYPE (DISH_TYPE_ID) ON DELETE SET NULL,
    CONSTRAINT DISH_DISH_PROVIDER_USER_ID_FK FOREIGN KEY (DISH_PROVIDER_USER_ID) REFERENCES PROVIDER (PROVIDER_USER_ID) ON DELETE SET NULL
);

CREATE TABLE DISH_GALLERY (
    DISH_GALLERY_ID      NUMBER NOT NULL,
    DISH_GALLERY_PHOTO   BLOB NOT NULL,
    DISH_GALLERY_DISH_ID NUMBER NOT NULL,
    CONSTRAINT DISH_GALLERY_PK PRIMARY KEY (DISH_GALLERY_ID),
    CONSTRAINT DISH_GALLERY_DISH_ID_FK FOREIGN KEY (DISH_GALLERY_DISH_ID) REFERENCES DISH (DISH_ID)
);

CREATE TABLE DISH_PRICE_HISTORY (
    DISH_PRICE_HISTORY_ID       NUMBER NOT NULL,
    DISH_PRICE_HISTORY_AMOUNT   FLOAT NOT NULL,
    DISH_PRICE_HISTORY_DATE     DATE NOT NULL,
    DISH_PRICE_HISTORY_DISH_ID  NUMBER NOT NULL,
    CONSTRAINT DISH_PRICE_HISTORY_PK PRIMARY KEY (DISH_PRICE_HISTORY_ID),
    CONSTRAINT DISH_PRICE_HISTORY_DISH_ID_FK FOREIGN KEY (DISH_PRICE_HISTORY_DISH_ID) REFERENCES DISH (DISH_ID)
);

CREATE TABLE DISH_REVIEW (
    DISH_REVIEW_ID       NUMBER NOT NULL,
    DISH_REVIEW_RATE     NUMBER NOT NULL,
    DISH_REVIEW_COMMENT  VARCHAR2(20) NOT NULL,
    DISH_REVIEW_DISH_ID  NUMBER NOT NULL,
    DISH_REVIEW_USER_ID  NUMBER NOT NULL,
    CONSTRAINT DISH_REVIEW_PK PRIMARY KEY (DISH_REVIEW_ID),
    CONSTRAINT DISH_REVIEW_DISH_REVIEW_USER_ID_FK FOREIGN KEY (DISH_REVIEW_USER_ID) REFERENCES CLIENT (CLIENT_USER_ID),
    CONSTRAINT DISH_REVIEW_DISH_REVIEW_DISH_ID_FK FOREIGN KEY (DISH_REVIEW_DISH_ID) REFERENCES DISH (DISH_ID)
);

CREATE TABLE DISH_TYPE (
    DISH_TYPE_ID         NUMBER NOT NULL,
    DISH_TYPE_TYPE       VARCHAR2(20) NOT NULL CHECK (DISH_TYPE_TYPE_CHK IN ('ENTRY', 'SOUP', 'STRONG_MEAL', 'DESSERT', 'DRINK')),
    CONSTRAINT DISH_TYPE_PK PRIMARY KEY (DISH_TYPE_ID)
);

CREATE TABLE ORDER (
    ORDER_ID             NUMBER NOT NULL,
    ORDER_AMOUNT         FLOAT NOT NULL,
    ORDER_DATE           DATE NOT NULL,
    ORDER_FEE            FLOAT NOT NULL,
    ORDER_DELIVERY_COST  FLOAT NOT NULL,
    ORDER_STATUS_DATE    DATE NOT NULL,
    ORDER_RECEIPT_FOLIO  CHAR(7) NULL,
    ORDER_DIG_SIGNATURE  BLOB NULL,
    ORDER_STATUS_ID      NUMBER NOT NULL,
    ORDER_CLIENT_ID      NUMBER NOT NULL,
    ORDER_DEALER_ID      NUMBER NULL,
    ORDER_CARD_ID        NUMBER NULL,
    CONSTRAINT ORDER_PK PRIMARY KEY (ORDER_ID),
    CONSTRAINT ORDER_ORDER_STATUS_ID_FK FOREIGN KEY (ORDER_STATUS_ID) REFERENCES ORDER_STATUS (ORDER_STATUS_ID) ON DELETE SET NULL,
    CONSTRAINT ORDER_ORDER_CARD_ID_FK FOREIGN KEY (ORDER_CARD_ID) REFERENCES CARD (CARD_ID) ON DELETE SET NULL,
    CONSTRAINT ORDER_ORDER_CLIENT_ID_FK FOREIGN KEY (ORDER_CLIENT_ID) REFERENCES CLIENT (CLIENT_USER_ID),
    CONSTRAINT ORDER_ORDER_DEALER_ID_FK FOREIGN KEY (ORDER_DEALER_ID) REFERENCES DEALER (DEALER_USER_ID) ON DELETE SET NULL
);

CREATE TABLE ORDER_DISH (
    ORDER_DISH_ID        NUMBER NOT NULL,
    ORDER_DISH_QUANTITY  NUMBER NOT NULL,
    ORDER_DISH_DISH_ID   NUMBER NOT NULL,
    ORDER_DISH_ORDER_ID  NUMBER NOT NULL,
    CONSTRAINT ORDER_DISH_PK PRIMARY KEY (ORDER_DISH_ID),
    CONSTRAINT ORDER_DISH_ORDER_ID_FK FOREIGN KEY (ORDER_DISH_ORDER_ID) REFERENCES ORDER (ORDER_ID),
    CONSTRAINT ORDER_DISH_DISH_ID_FK FOREIGN KEY (ORDER_DISH_DISH_ID) REFERENCES DISH (DISH_ID)
);

CREATE TABLE ORDER_REVIEW (
    ORDER_REVIEW_ID       NUMBER NOT NULL,
    ORDER_REVIEW_RATE     NUMBER NOT NULL,
    ORDER_REVIEW_COMMENT  VARCHAR2(100) NOT NULL,
    ORDER_REVIEW_ORDER_ID NUMBER NOT NULL,
    ORDER_REVIEW_USER_ID  NUMBER NOT NULL,
    CONSTRAINT ORDER_REVIEW_PK PRIMARY KEY (ORDER_REVIEW_ID),
    CONSTRAINT ORDER_REVIEW_ORDER_ID_FK FOREIGN KEY (ORDER_REVIEW_ORDER_ID) REFERENCES ORDER (ORDER_ID),
    CONSTRAINT ORDER_REVIEW_USER_ID_FK FOREIGN KEY (ORDER_REVIEW_USER_ID) REFERENCES CLIENT (CLIENT_USER_ID)
);

CREATE TABLE ORDER_STATUS (
    ORDER_STATUS_ID      NUMBER NOT NULL,
    ORDER_STATUS         VARCHAR2(20) NOT NULL CHECK (ORDER_STATUS_ORDER_STATUS_CHK IN ('REGISTERED', 'PAID', 'IN_PROCESS', 'SENT_TO_DEALER', 'DELIVERED', 'CANCELED', 'REJECTED')),
    CONSTRAINT ORDER_STATUS_PK PRIMARY KEY (ORDER_STATUS_ID)
);

CREATE TABLE ORDER_STATUS_HISTORY (
    ORDER_STATUS_HISTORY_ID         NUMBER NOT NULL,
    ORDER_STATUS_HISTORY_DATE       DATE NOT NULL,
    ORDER_STATUS_HISTORY_ORDER_ID   NUMBER NOT NULL,
    ORDER_STATUS_HISTORY_STATUS_ID  NUMBER NOT NULL,
    CONSTRAINT ORDER_STATUS_HISTORY_PK PRIMARY KEY (ORDER_STATUS_HISTORY_ID),
    CONSTRAINT ORDER_STATUS_HISTORY_ORDER_ID_FK FOREIGN KEY (ORDER_STATUS_HISTORY_ORDER_ID) REFERENCES ORDER (ORDER_ID),
    CONSTRAINT ORDER_STATUS_HISTORY_ORDER_STATUS_HISTORY_STATUS_ID_FK FOREIGN KEY (ORDER_STATUS_HISTORY_STATUS_ID) REFERENCES ORDER_STATUS (ORDER_STATUS_ID) ON DELETE SET NULL
);

CREATE TABLE PROVIDER (
    PROVIDER_USER_ID     NUMBER NOT NULL,
    PROVIDER_NAME        VARCHAR2(18) NOT NULL,
    PROVIDER_LOGO        BLOB NOT NULL,
    PROVIDER_DESCRIPTION VARCHAR2(1000) NOT NULL,
    CONSTRAINT PROVIDER_PK PRIMARY KEY (PROVIDER_USER_ID),
    CONSTRAINT PROVIDER_USER_ID_FK FOREIGN KEY (PROVIDER_USER_ID) REFERENCES USER(USER_ID) ON DELETE CASCADE
);

CREATE TABLE PROVIDER_BANK_DATA (
    PROVIDER_BANK_DATA_ID NUMBER NOT NULL,
    PROVIDER_BANK_DATA_CLABE VARCHAR(16) NOT NULL,
    PROVIDER_BANK_DATA_FREQUENCY VARCHAR2(20) NOT NULL CHECK (PROVIDER_BANK_DATA_FREQUENCY_CHK IN ('BIWEEKLY', 'WEEKLY', 'DAILY')),
    PROVIDER_BANK_DATA_BANK_ID NUMBER NOT NULL,
    PROVIDER_BANK_DATA_PROVIDER_ID NUMBER NOT NULL,
    CONSTRAINT PROVIDER_BANK_DATA_PK PRIMARY KEY (PROVIDER_BANK_DATA_ID),
    CONSTRAINT PROVIDER_BANK_DATA_PROVIDER_ID_FK FOREIGN KEY (PROVIDER_BANK_DATA_PROVIDER_ID) REFERENCES PROVIDER (PROVIDER_USER_ID),
    CONSTRAINT PROVIDER_BANK_DATA_BANK_ID_FK FOREIGN KEY (PROVIDER_BANK_DATA_BANK_ID) REFERENCES BANK (BANK_ID) ON DELETE SET NULL
);

CREATE TABLE PROVIDER_GALLERY (
    PROVIDER_GALLERY_ID  NUMBER NOT NULL,
    PROVIDER_GALLERY_PHOTO BLOB NOT NULL,
    PROVIDER_GALLERY_USER_ID NUMBER NOT NULL,
    CONSTRAINT PROVIDER_GALLERY_PK PRIMARY KEY (PROVIDER_GALLERY_ID),
    CONSTRAINT PROVIDER_GALLERY_USER_ID_FK FOREIGN KEY (PROVIDER_GALLERY_USER_ID) REFERENCES PROVIDER (PROVIDER_USER_ID)
);

CREATE TABLE PROVIDER_PAYMENT (
    PROVIDER_PAYMENT_ID  NUMBER NOT NULL,
    PROVIDER_PAYMENT_AMOUNT FLOAT NOT NULL,
    PROVIDER_PAYMENT_DATE DATE NOT NULL,
    PROVIDER_PAYMENT_USER_ID NUMBER NULL,
    CONSTRAINT PROVIDER_PAYMENT_PK PRIMARY KEY (PROVIDER_PAYMENT_ID),
    CONSTRAINT PROVIDER_PAYMENT_PROVIDER_PAYMENT_USER_ID_FK FOREIGN KEY (PROVIDER_PAYMENT_USER_ID) REFERENCES PROVIDER (PROVIDER_USER_ID) ON DELETE SET NULL
);