-- Índices en Claves Foráneas
CREATE INDEX IDX_CARD_CLIENT_ID ON CARD (CARD_CLIENT_ID);

CREATE INDEX IDX_DEALER_BANK_DEALER_ID ON DEALER_BANK_DATA (DEALER_BANK_DEALER_ID);

CREATE INDEX IDX_DEALER_PAYMENT_DEALER_ID ON DEALER_PAYMENT (DEALER_PAYMENT_DEALER_ID);

CREATE INDEX IDX_DISH_PROVIDER_USER_ID ON DISH (DISH_PROVIDER_USER_ID);

CREATE INDEX IDX_DISH_GALLERY_DISH_ID ON DISH_GALLERY (DISH_GALLERY_DISH_ID);

CREATE INDEX IDX_DISH_PRICE_HISTORY_DISH_ID ON DISH_PRICE_HISTORY (DISH_PRICE_HISTORY_DISH_ID);

CREATE INDEX IDX_DISH_REVIEW_USER_ID ON DISH_REVIEW (DISH_REVIEW_USER_ID);
CREATE INDEX IDX_DISH_REVIEW_DISH_ID ON DISH_REVIEW (DISH_REVIEW_DISH_ID);

CREATE INDEX IDX_LOCATION_LOG_USER_ID ON LOCATION_LOG (LOCATION_LOG_USER_ID);

CREATE INDEX IDX_ORDER_CLIENT_ID ON ORDER (ORDER_CLIENT_ID);
CREATE INDEX IDX_ORDER_DEALER_ID ON ORDER (ORDER_DEALER_ID);

CREATE INDEX IDX_ORDER_DISH_DISH_ID ON ORDER_DISH (ORDER_DISH_DISH_ID);

CREATE INDEX IDX_ORDER_STATUS_HISTORY_ORDER_ID ON ORDER_STATUS_HISTORY (ORDER_STATUS_HISTORY_ORDER_ID);
CREATE INDEX IDX_ORDER_STATUS_HISTORY_STATUS_ID ON ORDER_STATUS_HISTORY (ORDER_STATUS_HISTORY_STATUS_ID);

CREATE INDEX IDX_PROVIDER_BANK_DATA_PROVIDER_ID ON PROVIDER_BANK_DATA (PROVIDER_BANK_DATA_PROVIDER_ID);

CREATE INDEX IDX_PROVIDER_GALLERY_USER_ID ON PROVIDER_GALLERY (PROVIDER_GALLERY_USER_ID);

CREATE INDEX IDX_PROVIDER_PAYMENT_USER_ID ON PROVIDER_PAYMENT (PROVIDER_PAYMENT_USER_ID);

-- Índices en Columnas de Búsqueda Común
CREATE UNIQUE INDEX UIDX_USER_USERNAME ON USER (USER_USERNAME);
CREATE UNIQUE INDEX UIDX_USER_EMAIL ON USER (USER_EMAIL);

-- Índices Compuestos para Consultas Específicas
CREATE INDEX IDX_ORDER_CLIENT_STATUS ON ORDER (ORDER_CLIENT_ID, ORDER_STATUS_ID);
CREATE INDEX IDX_DISH_TYPE_CATEGORY ON DISH (DISH_TYPE_ID, DISH_CATEGORY);

-- Índices en Columnas Utilizadas en Ordenamientos y Agrupamientos
CREATE INDEX IDX_ORDER_DATE ON ORDER (ORDER_DATE);
CREATE INDEX IDX_ORDER_AMOUNT ON ORDER (ORDER_AMOUNT);

CREATE INDEX IDX_LOCATION_LOG_TIMESTAMP ON LOCATION_LOG (LOCATION_LOG_TIMESTAMP);

-- Índices en Columnas de Fecha y Hora
CREATE INDEX IDX_DEALER_PAYMENT_DATE ON DEALER_PAYMENT (DEALER_PAYMENT_DATE);
CREATE INDEX IDX_PROVIDER_PAYMENT_DATE ON PROVIDER_PAYMENT (PROVIDER_PAYMENT_DATE);
CREATE INDEX IDX_ORDER_STATUS_HISTORY_DATE ON ORDER_STATUS_HISTORY (ORDER_STATUS_HISTORY_DATE);

-- Índices en Columnas Numéricas Frecuentemente Consultadas
CREATE INDEX IDX_DISH_CALORIES ON DISH (DISH_CALORIES);
CREATE INDEX IDX_ORDER_DISH_QUANTITY ON ORDER_DISH (ORDER_DISH_QUANTITY);