--@Autor: Navarrete Zamora Aldo Yael y Diego Ignacio Nuñez Hernandez
--@Fecha creación: 07/06/2024 TODO:
--@Descripción: Probar conexiones

whenever sqlerror exit rollback;

spool s-05-probar-conexiones.log

Prompt Conectando como usuario sys...

connect sys/system1 as sysdba

Prompt viendo en qué modo de conexión estamos
Pause [Enter] ¿Funcionó el modo de conexión?...

Prompt Probando la conexión
Prompt conectando NAPROYNU_MODULO_1...
connect sys/system1@NAPROYNU_MODULO_1 as sysdba;
Pause [Enter] ¿Funcionó el modo de conexión?...

Prompt conectando NAPROYNU_MODULO_1_SHARED...
connect sys/system1@NAPROYNU_MODULO_1_SHARED as sysdba;
Pause [Enter] ¿Funcionó el modo de conexión?...

Prompt conectando NAPROYNU_MODULO_1_DEDICATED...
connect sys/system1@NAPROYNU_MODULO_1_DEDICATED as sysdba;
Pause [Enter] ¿Funcionó el modo de conexión?...

Prompt conectando NAPROYNU_MODULO_1_POOLED...
connect sys/system1@NAPROYNU_MODULO_1_POOLED as sysdba;
Pause [Enter] ¿Funcionó el modo de conexión?...

Prompt conectando NAPROYNU_MODULO_2...
connect sys/system1@NAPROYNU_MODULO_2 as sysdba;
Pause [Enter] ¿Funcionó el modo de conexión?...

Prompt conectando NAPROYNU_MODULO_2_SHARED...
connect sys/system1@NAPROYNU_MODULO_2_SHARED as sysdba;
Pause [Enter] ¿Funcionó el modo de conexión?...

Prompt conectando NAPROYNU_MODULO_2_DEDICATED...
connect sys/system1@NAPROYNU_MODULO_2_DEDICATED as sysdba;
Pause [Enter] ¿Funcionó el modo de conexión?...

Prompt conectando NAPROYNU_MODULO_2_POOLED...
connect sys/system1@NAPROYNU_MODULO_2_POOLED as sysdba;
Pause [Enter] ¿Funcionó el modo de conexión?...

spool off

exit;